name: Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Build documentation
        run: cargo doc --verbose --no-deps
      - name: Write CNAME file
        run: echo 'iced-dialog.pml68.dev' > ./target/doc/CNAME
      - name: Copy redirect file as index.html
        run: cp docs/redirect.html target/doc/index.html
      - name: Deploy documentation
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          force_orphan: true
